# Row Echelon / Reduced Row Echelon Form Calculator
### By Chris Keiningham
- Using numpy arrays
- A matrix is said to be in Row-Echelon Form when for each nonzero entry, all the entries to its left and below it are equal to zero
- A matrix is said to be in Reduced Row-Echelon Form when each nonzero leading coefficient is 1, and all other entries are 0

In [1]:
import numpy as np

In [5]:
matrix = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 11, 11, 12]
])

In [6]:
def swapRows(matrix, row1, row2):
    matrix[[row1, row2]] = matrix[[row2, row1]]

def gaussElimination(matrix, rref=False, printing=False):
    
    nRows, nCols = matrix.shape

    if printing:
        np.set_printoptions(suppress=True)
        print("Original Matrix:")
        print(matrix, end="\n\n")

    # Iterate through each row
    for i in range(nRows):
        
        # Get the pivot value
        pivot = matrix[i][i]
        foundNonzero = False

        # Find the first nonzero pivot, or skip row
        if pivot == 0:
            # Iterate over all subsequent rows
            for j in range(i + 1, nRows):
                # Check the i'th position on each subsequent row for a nonzero entry
                if matrix[j][i] != 0:
                    # Swap in place
                    swapRows(matrix, i, j)

                    # Set the pivot to the newly found nonzero entry
                    pivot = matrix[i][i]
                    foundNonzero = True
                    
                    if printing:
                        print(f"Swapped rows {i+1} and {j+1}:")
                        print(matrix, end="\n\n")
                        
                    break

            # If no nonzero entry was found, skip the position
            if not foundNonzero:
                continue        

        # Divide the whole row by the pivot
        matrix[i] = matrix[i] / pivot
        
        if printing:
            print(f"Divide row {i+1} by {pivot}:")
            print(matrix, end="\n\n")

        # 0 out each entry below current entry in place
        for k in range(i + 1, nRows):
            multiplier = matrix[k][i] * -1
            matrix[k] += matrix[i] * multiplier

        if printing and i + 1 != nRows:
            print(f"Zero out entries below A{i+1},{i+1}:")
            print(matrix, end="\n\n")

        # If we wish to perform Gauss Jordan Elimination and reduce to Reduced Row Echelon Form
        if rref:
            # Zero out each entry above current entry in place
            for k in range(i - 1, -1, -1):
                multiplier = matrix[k][i] * -1
                matrix[k] += matrix[i] * multiplier
                
            if printing and i + 1 != 1:
                    print(f"Zero out entries above A{i+1},{i+1}:")
                    print(matrix, end="\n\n")

    if printing:
        if rref:
            print("Matrix in Reduced Row Echelon Form:")
        else:
            print("Matrix in Row Echelon Form:")
        print(matrix, end="\n\n")

In [8]:
gaussElimination(matrix, rref=False, printing=True)

Original Matrix:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 11 11 12]]

Before divide
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 11 11 12]]
After divide
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 11 11 12]]
Divide row 1 by 1:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 11 11 12]]

Zero out entries below A1,1:
[[  1   2   3   4]
 [  0  -4  -8 -12]
 [  0  -7 -16 -24]]

Before divide
 [[  1   2   3   4]
 [  0  -4  -8 -12]
 [  0  -7 -16 -24]]
After divide
 [[  1   2   3   4]
 [  0   1   2   3]
 [  0  -7 -16 -24]]
Divide row 2 by -4:
[[  1   2   3   4]
 [  0   1   2   3]
 [  0  -7 -16 -24]]

Zero out entries below A2,2:
[[ 1  2  3  4]
 [ 0  1  2  3]
 [ 0  0 -2 -3]]

Before divide
 [[ 1  2  3  4]
 [ 0  1  2  3]
 [ 0  0 -2 -3]]
After divide
 [[1 2 3 4]
 [0 1 2 3]
 [0 0 1 1]]
Divide row 3 by -2:
[[1 2 3 4]
 [0 1 2 3]
 [0 0 1 1]]

Matrix in Row Echelon Form:
[[1 2 3 4]
 [0 1 2 3]
 [0 0 1 1]]



In [ ]:
gaussElimination(matrix, rref=True, printing=True)

In [219]:
# Example matrices
matrices = [
    np.array([
        [1, 2, 3],
        [0, 3, 4],
        [0, 0, 5]
    ]),
    np.array([
        [1, 0, 0],
        [0, 2, 3],
        [0, 0, 0]
    ]),
    np.array([
        [1, 2, 1, 3],
        [0, 2, 1, 1],
        [0, 0, 3, 4]
    ]),
    np.array([
        [1, 2, 3, 4],
        [0, 0, 1, 2],
        [0, 0, 0, 5]
    ]),
      np.array([
        [1, 2, 3, 4],
        [0, 0, 0, 2],
        [0, 0, 0, 0]
    ]),
        np.array([
        [0, 0, 0],
        [1, 0, 0],
        [0, 1, 0]
    ]),
    np.array([
        [0, 1, 0],
        [0, 0, 1],
        [1, 0, 0]
    ]),
        np.array([
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]
    ]),
        np.array([
        [0, 1, 1],
        [0, 0, 0],
        [0, 0, 0]
    ])
]